In [1]:
#Dependencies
import pandas as pd
import numpy as np
import requests
import json

In [2]:
from config import gkey
ta_pd = pd.read_csv("tourist_attraction.csv")
ta_pd.head()

,locations,address,lat,lon
0,Carowinds,"300 Carowinds Blvd, Charlotte, NC 28273",NaN,NaN
1,U.S. National Whitewater Center,"5000 Whitewater Center Pkwy, Charlotte, NC 28214",NaN,NaN
2,NASCAR Hall of Fame,"400 E M.L.K. Jr Blvd, Charlotte, NC 28202",NaN,NaN
3,Discovery Place Science,"301 N Tryon St, Charlotte, NC 28202",NaN,NaN
4,Billy Graham Library,"4330 Westmont Dr, Charlotte, NC 28217",NaN,NaN

In [3]:
params = {"key": gkey}
#Loop through the cities and run a lat long search
for index, row in ta_pd.iterrows():
    base_url ="https://maps.googleapis.com/maps/api/geocode/json"
    
    address = row ['address']
    #update address key value
    params ['address'] = f"{address}"
    lat_lng = requests.get(base_url, params=params)
# print(lat_lng.url)
    lat_lng = lat_lng.json()
    ta_pd.loc[index, "lat"] = lat_lng["results"][0]["geometry"]["location"]["lat"]
    ta_pd.loc[index, "lon"] = lat_lng["results"][0]["geometry"]["location"]["lng"]
ta_pd.head()

,locations,address,lat,lon
0,Carowinds,"300 Carowinds Blvd, Charlotte, NC 28273",35.104223,-80.942811
1,U.S. National Whitewater Center,"5000 Whitewater Center Pkwy, Charlotte, NC 28214",35.280574,-80.986994
2,NASCAR Hall of Fame,"400 E M.L.K. Jr Blvd, Charlotte, NC 28202",35.221325,-80.843408
3,Discovery Place Science,"301 N Tryon St, Charlotte, NC 28202",35.229298,-80.840806
4,Billy Graham Library,"4330 Westmont Dr, Charlotte, NC 28217",35.190373,-80.909281

In [4]:
ta_pd.to_html('top_attractions')